/**
 * Emisor de la migración Flyway `V1__init.sql` (tarea 3.1, D4, D11).
 *
 * Hasta esta tarea el ZIP traía entidades JPA con `ddl-auto=validate` y ninguna
 * migración que las respaldara: el proyecto compilaba (`mvnw -q verify`) pero
 * **fallaba al arrancar** contra PostgreSQL 17, porque `validate` no encontraba
 * la tabla. Con este archivo el ZIP sí se sostiene solo, y esa es la mitad de
 * SC-F10 que el reporte de la Fase 2 declaró pendiente.
 *
 * Las tres reglas que este emisor NO puede romper:
 *
 * 1. **Los nombres SQL salen de la IR, nunca de la estrategia de Hibernate**
 *    (D4). Cada tabla usa `entity.table` y cada columna `field.column` — el
 *    MISMO campo que `@Table(name = …)`/`@Column(name = …)` en `entity.ts`. Si
 *    el DDL y el JPA leyeran de fuentes distintas, bastaría una diferencia en
 *    un caso borde para que `validate` falle al arrancar con un modelo que
 *    compiló bien.
 * 2. **Los identificadores van SIN comillas** (D3, corrección FR-D20b):
 *    `CREATE TABLE dirección (` y `código_postal varchar(255)`. PostgreSQL 17
 *    acepta letras acentuadas en un identificador sin comillas, y el golden de
 *    la Fase 0 (0.10) confirmó que `validate` no reporta discrepancia entre la
 *    entidad `Dirección`/`códigoPostal` y la tabla `dirección`/`código_postal`.
 *    El límite de 63 **bytes UTF-8** lo aplica la tubería de `java-names.ts`
 *    (`tableName`/`columnName`), que es la única que puede recortar: acá se
 *    escribe el nombre ya resuelto, sin volver a medirlo.
 * 3. **Sin claves foráneas** (FR-F06, SC-F10): las relaciones son de
 *    `codegen-relationships`, y esta rebanada no emite ninguna. La PK va inline
 *    (`PRIMARY KEY (<columna>)`), porque Hibernate no valida nombres de
 *    constraint y así el emisor no tiene que inventar uno que quepa en 63 bytes.
 *
 * Función pura: sin reloj, sin azar, sin locale. El orden de las tablas es el
 * de las entidades en la IR, que es estable (D7).
 */

import type { CodegenIr, IrEntity, IrField } from '../codegen-ir';
import type { GeneratedFile } from '../zip';

/** Ruta de la migración dentro del ZIP (D11): la que Flyway descubre al arrancar. */
const MIGRATION_PATH = 'src/main/resources/db/migration/V1__init.sql';

/** Sangría del SQL: cuatro espacios, igual que el golden de la Fase 0. */
const INDENT = '    ';

/**
 * Definición de una columna. `field.nullable` en la IR significa
 * «`lowerBound < 1`», así que un campo NO nulo (`nullable === false`) lleva
 * `NOT NULL`, igual que su `@Column(nullable = false)`.
 *
 * La PK con `IDENTITY` es la excepción: una columna
 * `GENERATED BY DEFAULT AS IDENTITY` ya es implícitamente `NOT NULL`, y D5 fija
 * esa forma para `Integer`/`Long`. La PK `UUID` no lleva default — la genera
 * Hibernate con `GenerationType.UUID`, no `gen_random_uuid()`— y por eso sale
 * con el `NOT NULL` normal.
 */
function columnDefinition(field: IrField): string {
  const parts = [field.column, field.type.sql];
  if (field.isId && field.generation === 'IDENTITY') {
    parts.push('GENERATED BY DEFAULT AS IDENTITY');
  } else if (!field.nullable) {
    parts.push('NOT NULL');
  }
  return `${INDENT}${parts.join(' ')}`;
}

/**
 * `CREATE TABLE` de una entidad: sus columnas en el orden de la IR y la PK al
 * final. `buildIr` garantiza que toda entidad emitible tiene una PK —declarada
 * válida o inyectada—; una entidad con `pk_type_invalid` bloquea y nunca llega
 * acá.
 */
function createTable(entity: IrEntity): string {
  const id = entity.fields.find((field) => field.isId);
  if (id === undefined) {
    throw new Error(`la IR de ${entity.name} no tiene clave primaria y no está bloqueada`);
  }
  const lines = entity.fields.map(columnDefinition);
  lines.push(`${INDENT}PRIMARY KEY (${id.column})`);
  return `CREATE TABLE ${entity.table} (\n${lines.join(',\n')}\n);`;
}

/** El texto completo de `V1__init.sql`. Un `CREATE TABLE` por entidad, ninguno por enum. */
export function emitFlywayMigration(ir: CodegenIr): string {
  const header = [
    '-- Esquema inicial generado por UMLive.',
    '-- Una tabla por entidad, sin claves foraneas: las relaciones son de codegen-relationships.',
    '-- Los identificadores son los mismos que declara el JPA, para que ddl-auto=validate los acepte.',
  ];
  const statements = ir.entities.map(createTable);
  return `${[...header, ...statements].join('\n\n')}\n`;
}

/** `db/migration/V1__init.sql` para el ZIP (D11). */
export function emitFlywayFile(ir: CodegenIr): GeneratedFile {
  return { path: MIGRATION_PATH, content: emitFlywayMigration(ir) };
}
